# environment setup
language: swift
osx_image: xcode11.1

# run jobs on changes to master only
branches:
  only:
    - develop

# prepare dependency managers
before_install:
  - brew update
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"

# install dependencies
install:
  - bundle install

# jobs and stages to run
jobs:
  include:
    - stage: "Test"
      name: "Unit tests"
      script:
        - bundle exec fastlane run_all_tests
